#!/usr/bin/env python3
import random
hezkeveci = ['masaz', 'kompliment', 'dat cokoladu', 'objeti', 'pusinku na celicko', 'vecere', 'dopis', 'kvetina', 'makronek', 'poskrabkat']


def dnesnivec():
	vec = random.choice(hezkeveci)
	print(vec)

dnesnivec()
